version: '3'
services:
  go-web-server:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - server_go_module_data:/go
    ports:
      # ローカルのポート被らないように
      # 3112は適当
      - "3112:80"
  goroutine-scraping-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./api/:/app
      - api_go_module_data:/go
volumes:
  api_go_module_data:
  server_go_module_data:
