version: '3'
services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - .:/app
  goroutine-scraping-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: goroutine-scraping-api:latest
    volumes:
      - ./api/:/app
      - go_module_data:/go

volumes:
  go_module_data:
