version: '3'
services:
  goroutine-scraping-cli:
    build:
      context: .
      dockerfile: Dockerfile
    image: goroutine-scraping-cli:latest
    volumes:
      - ./:/app
      - go_module_data:/go

volumes:
  go_module_data:
